import { useRef, useState } from 'react';
import Box from "@mui/material/Box";
import Button from "@mui/material/Button";
import Card from "@mui/material/Card";
import CardContent from "@mui/material/CardContent";
import Stack from "@mui/material/Stack";
import Typography from "@mui/material/Typography";
import CircularProgress from "@mui/material/CircularProgress";
import Chip from "@mui/material/Chip";
import LinearProgress from "@mui/material/LinearProgress";
import { BarChart } from "@mui/x-charts/BarChart";
import { Gauge } from "@mui/x-charts/Gauge";
import { PieChart } from "@mui/x-charts/PieChart";
import { LineChart } from "@mui/x-charts/LineChart";
import { DataGrid } from '@mui/x-data-grid';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';

const columns = [
    { field: 'id', headerName: 'ID', width: 70 },
    { field: 'reportName', headerName: 'Report Name', width: 180 },
    { field: 'category', headerName: 'Category', width: 130 },
    { field: 'generatedBy', headerName: 'Generated By', width: 150 },
    { field: 'date', headerName: 'Date', width: 130 },
    {
        field: 'status',
        headerName: 'Status',
        width: 120,
        renderCell: (params) => (
            <Chip
                label={params.value}
                size="small"
                sx={{
                    backgroundColor: params.value === 'Completed' ? C.midGreen : params.value === 'Pending' ? C.yellow : C.paleGreen,
                    color: C.dark,
                    fontWeight: 700,
                    fontSize: '0.7rem',
                }}
            />
        ),
    },
];

const rows = [
    { id: 1, reportName: 'Q1 Sales Summary', category: 'Sales', generatedBy: 'Admin', date: '2025-01-15', status: 'Completed' },
    { id: 2, reportName: 'User Growth Report', category: 'Users', generatedBy: 'Admin', date: '2025-01-22', status: 'Completed' },
    { id: 3, reportName: 'Inventory Audit', category: 'Inventory', generatedBy: 'Manager', date: '2025-02-03', status: 'Pending' },
    { id: 4, reportName: 'Finance Overview', category: 'Finance', generatedBy: 'Admin', date: '2025-02-10', status: 'Completed' },
    { id: 5, reportName: 'Q1 User Retention', category: 'Users', generatedBy: 'Analyst', date: '2025-02-18', status: 'In Review' },
    { id: 6, reportName: 'March Sales Detail', category: 'Sales', generatedBy: 'Admin', date: '2025-03-05', status: 'Completed' },
    { id: 7, reportName: 'Stock Level Check', category: 'Inventory', generatedBy: 'Manager', date: '2025-03-12', status: 'Completed' },
    { id: 8, reportName: 'Budget Allocation', category: 'Finance', generatedBy: 'Admin', date: '2025-03-20', status: 'Pending' },
    { id: 9, reportName: 'April Sales Forecast', category: 'Sales', generatedBy: 'Analyst', date: '2025-04-01', status: 'Completed' },
];

// Color scheme
const C = {
    dark: '#283618',
    lightYellow: '#ecf39e',
    midGreen: '#90a955',
    paleGreen: '#dde5b6',
    yellow: '#ffe566',
};

const statCards = [
    { label: 'Total Generated', value: '89', sub: '+12 from last cycle', trend: '+14%' },
    { label: 'Total Completed', value: '71', sub: '+8 from last cycle', trend: '+13%' },
    { label: 'Completion Rate', value: '78%', sub: 'Current cycle', trend: '+2%' },
    { label: 'Active Categories', value: '4', sub: 'Sales · Users · Inv · Fin', trend: null },
];

const categoryProgress = [
    { label: 'Sales', completed: 18, total: 22, color: C.dark },
    { label: 'Users', completed: 14, total: 18, color: C.midGreen },
    { label: 'Inventory', completed: 10, total: 14, color: C.yellow },
    { label: 'Finance', completed: 9, total: 12, color: C.paleGreen },
];

const ReportsPage = () => {
    const printRef = useRef(null);
    const [exporting, setExporting] = useState(false);

    // Builds the PDF blob from the printRef DOM node and returns it.
    const buildPDF = async () => {
        const printContent = printRef.current;
        if (!printContent) return null;

        const exportedAt = new Intl.DateTimeFormat('en-US', {
            dateStyle: 'long',
            timeStyle: 'short',
        }).format(new Date());

        const canvas = await html2canvas(printContent, {
            scale: 2,
            useCORS: true,
            backgroundColor: '#ffffff',
            logging: false,
            scrollX: 0,
            scrollY: -window.scrollY,
            windowWidth: document.documentElement.scrollWidth,
            windowHeight: document.documentElement.scrollHeight,
        });

        const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
        const pageWidth  = pdf.internal.pageSize.getWidth();
        const pageHeight = pdf.internal.pageSize.getHeight();
        const margin      = 16;
        const usableWidth = pageWidth - margin * 2;
        const headerHeight = 34;

        // Header
        pdf.setFontSize(22);
        pdf.setTextColor(40, 54, 24);
        pdf.text('Reports Summary', margin, margin + 6);

        pdf.setFontSize(10);
        pdf.setTextColor(107, 114, 128);
        pdf.text(
            'Analytics overview for generated reports, category breakdown, and completion performance.',
            margin, margin + 13, { maxWidth: usableWidth }
        );
        pdf.text(`Prepared on ${exportedAt}`, margin, margin + 22);

        pdf.setDrawColor(144, 169, 85);
        pdf.setLineWidth(0.5);
        pdf.line(margin, margin + 26, pageWidth - margin, margin + 26);

        // Paginate canvas
        const imgWidth       = usableWidth;
        const totalImgHeight = (canvas.height * imgWidth) / canvas.width;
        let remainingMM = totalImgHeight;
        let sourcePxY   = 0;
        let isFirstPage = true;

        while (remainingMM > 0) {
            const topY         = isFirstPage ? margin + headerHeight : margin;
            const availableMM  = pageHeight - topY - margin;
            const sliceMM      = Math.min(remainingMM, availableMM);
            const pxPerMM      = canvas.width / imgWidth;
            const slicePx      = Math.round(sliceMM * pxPerMM);

            const sliceCanvas  = document.createElement('canvas');
            sliceCanvas.width  = canvas.width;
            sliceCanvas.height = slicePx;
            sliceCanvas.getContext('2d').drawImage(
                canvas,
                0, sourcePxY, canvas.width, slicePx,
                0, 0,         canvas.width, slicePx
            );

            pdf.addImage(sliceCanvas.toDataURL('image/png'), 'PNG', margin, topY, imgWidth, sliceMM);

            remainingMM -= sliceMM;
            sourcePxY   += slicePx;
            if (remainingMM > 0) pdf.addPage();
            isFirstPage = false;
        }

        return pdf;
    };

    // Export button → renders charts via html2canvas, builds a PDF blob,
    // opens it in a new tab so the browser shows a proper PDF preview,
    // then auto-triggers the native print dialog which includes
    // "Save as PDF" as a destination option.
    const handleExport = async () => {
        setExporting(true);
        try {
            const pdf = await buildPDF();
            if (!pdf) return;

            const blob    = pdf.output('blob');
            const blobUrl = URL.createObjectURL(blob);
            const win     = window.open(blobUrl, '_blank');

            if (win) {
                win.addEventListener('load', () => {
                    win.focus();
                    win.print();
                });
            }

            // Release the object URL after a minute
            setTimeout(() => URL.revokeObjectURL(blobUrl), 60_000);
        } catch (err) {
            console.error('Export failed:', err);
        } finally {
            setExporting(false);
        }
    };

    const sharedBtnDisabled = { '&.Mui-disabled': { borderColor: C.paleGreen, color: C.paleGreen } };

    return (
        <Box>
            {/* ── Page Header ─────────────────────────────────────────── */}
            <Box
                sx={{
                    mb: 4, p: 3, borderRadius: 3,
                    backgroundColor: C.dark,
                    display: 'flex',
                    flexDirection: { xs: 'column', md: 'row' },
                    justifyContent: 'space-between',
                    alignItems: { xs: 'flex-start', md: 'center' },
                    gap: 2,
                }}
            >
                <Box>
                    <Typography variant="h4" sx={{ color: C.lightYellow, fontWeight: 700, mb: 0.5 }}>
                        Reports
                    </Typography>
                    <Typography variant="body2" sx={{ color: C.paleGreen }}>
                        Analytics overview — generated reports, category breakdown, and completion performance.
                    </Typography>
                </Box>

                <Stack direction="row" spacing={1.5} flexWrap="wrap" useFlexGap>
                    <Button
                        variant="contained"
                        sx={{
                            backgroundColor: C.midGreen, color: C.dark, fontWeight: 700,
                            '&:hover': { backgroundColor: C.lightYellow },
                        }}
                    >
                        Generate
                    </Button>

                    <Button
                        variant="outlined"
                        onClick={handleExport}
                        disabled={exporting}
                        startIcon={exporting ? <CircularProgress size={14} sx={{ color: C.lightYellow }} /> : null}
                        sx={{
                            borderColor: C.lightYellow, color: C.lightYellow, fontWeight: 600,
                            '&:hover': { borderColor: C.yellow, color: C.yellow, backgroundColor: 'transparent' },
                            ...sharedBtnDisabled,
                        }}
                    >
                        {exporting ? 'Exporting…' : 'Export'}
                    </Button>

                    <Button
                        variant="outlined"
                        sx={{
                            borderColor: C.paleGreen, color: C.paleGreen, fontWeight: 600,
                            '&:hover': { borderColor: C.lightYellow, color: C.lightYellow, backgroundColor: 'transparent' },
                        }}
                    >
                        Filter
                    </Button>
                </Stack>
            </Box>

            {/* ── Printable content ───────────────────────────────────── */}
            <Box ref={printRef}>

                {/* Stat Cards */}
                <Box
                    sx={{
                        display: 'grid',
                        gridTemplateColumns: { xs: '1fr 1fr', md: 'repeat(4, 1fr)' },
                        gap: 2, mb: 3,
                    }}
                >
                    {statCards.map((stat, i) => (
                        <Card
                            key={i}
                            sx={{
                                backgroundColor: i % 2 === 0 ? C.paleGreen : C.lightYellow,
                                border: 'none', boxShadow: 'none', borderRadius: 3,
                            }}
                        >
                            <CardContent>
                                <Typography
                                    variant="body2"
                                    sx={{ color: C.dark, fontWeight: 600, opacity: 0.7, mb: 0.5, fontSize: '0.75rem', textTransform: 'uppercase', letterSpacing: 1 }}
                                >
                                    {stat.label}
                                </Typography>
                                <Box sx={{ display: 'flex', alignItems: 'baseline', gap: 1 }}>
                                    <Typography variant="h4" sx={{ color: C.dark, fontWeight: 800, lineHeight: 1 }}>
                                        {stat.value}
                                    </Typography>
                                    {stat.trend && (
                                        <Typography variant="caption" sx={{ color: C.dark, fontWeight: 700, backgroundColor: C.midGreen, px: 0.8, py: 0.2, borderRadius: 1 }}>
                                            {stat.trend}
                                        </Typography>
                                    )}
                                </Box>
                                <Typography variant="caption" sx={{ color: C.dark, opacity: 0.6 }}>
                                    {stat.sub}
                                </Typography>
                            </CardContent>
                        </Card>
                    ))}
                </Box>

                <Stack spacing={3}>
                    {/* ── Row 1: Bar Chart + Category Progress ─────────── */}
                    <Stack direction={{ xs: 'column', lg: 'row' }} spacing={3}>
                        <Card sx={{ flex: 2, borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                        Monthly Report Output
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        Reports generated vs. completed across the last four months.
                                    </Typography>
                                </Box>
                                <BarChart
                                    series={[
                                        { data: [18, 24, 20, 27], label: "Generated", color: C.dark },
                                        { data: [12, 19, 17, 23], label: "Completed", color: C.midGreen },
                                    ]}
                                    height={260}
                                    xAxis={[{ data: ["January", "February", "March", "April"], scaleType: "band", label: "Month" }]}
                                />
                            </CardContent>
                        </Card>

                        <Card sx={{ flex: 1, borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                        Category Progress
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        Completed vs. total per category.
                                    </Typography>
                                </Box>
                                <Stack spacing={2.5} sx={{ mt: 1 }}>
                                    {categoryProgress.map((cat) => (
                                        <Box key={cat.label}>
                                            <Box sx={{ display: 'flex', justifyContent: 'space-between', mb: 0.5 }}>
                                                <Typography variant="body2" sx={{ fontWeight: 700, color: C.dark }}>
                                                    {cat.label}
                                                </Typography>
                                                <Typography variant="body2" sx={{ color: C.dark, opacity: 0.7 }}>
                                                    {cat.completed}/{cat.total}
                                                </Typography>
                                            </Box>
                                            <LinearProgress
                                                variant="determinate"
                                                value={(cat.completed / cat.total) * 100}
                                                sx={{
                                                    height: 10, borderRadius: 5,
                                                    backgroundColor: C.paleGreen,
                                                    '& .MuiLinearProgress-bar': { backgroundColor: C.dark, borderRadius: 5 },
                                                }}
                                            />
                                        </Box>
                                    ))}
                                </Stack>
                            </CardContent>
                        </Card>
                    </Stack>

                    {/* ── Row 2: Trend Line + Pie + Gauge ──────────────── */}
                    <Stack direction={{ xs: 'column', lg: 'row' }} spacing={3}>
                        <Card sx={{ flex: 1, borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                        Weekly Completion Trend
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        Reports completed week-over-week this quarter.
                                    </Typography>
                                </Box>
                                <LineChart
                                    series={[{ data: [4, 6, 5, 9, 7, 11, 10, 13, 12, 15, 14, 17], label: 'Completed', color: C.midGreen, area: true }]}
                                    xAxis={[{ data: ['W1','W2','W3','W4','W5','W6','W7','W8','W9','W10','W11','W12'], scaleType: 'band' }]}
                                    height={220}
                                    sx={{ '& .MuiLineElement-root': { strokeWidth: 2 }, '& .MuiAreaElement-root': { fill: C.paleGreen, fillOpacity: 0.5 } }}
                                />
                            </CardContent>
                        </Card>

                        <Card sx={{ flex: 1, borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                        Category Share
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        Distribution by category this period.
                                    </Typography>
                                </Box>
                                <Box sx={{ display: "flex", justifyContent: "center" }}>
                                    <PieChart
                                        series={[{
                                            data: [
                                                { id: 0, value: 14, label: "Sales",     color: C.dark },
                                                { id: 1, value: 10, label: "Users",     color: C.midGreen },
                                                { id: 2, value: 8,  label: "Inventory", color: C.lightYellow },
                                                { id: 3, value: 6,  label: "Finance",   color: C.yellow },
                                            ],
                                        }]}
                                        width={260}
                                        height={200}
                                    />
                                </Box>
                            </CardContent>
                        </Card>

                        <Card sx={{ flex: 1, borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                            <CardContent>
                                <Box sx={{ mb: 2 }}>
                                    <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                        Completion Rate
                                    </Typography>
                                    <Typography variant="body2" color="text.secondary">
                                        On-time completion for the latest cycle.
                                    </Typography>
                                </Box>
                                <Box sx={{ minHeight: 200, display: "flex", flexDirection: 'column', alignItems: "center", justifyContent: "center", gap: 1 }}>
                                    <Gauge
                                        width={160} height={160} value={78}
                                        sx={{
                                            '& .MuiGauge-valueText': { fill: C.dark, fontWeight: 700 },
                                            '& .MuiGauge-referenceArc': { fill: C.paleGreen },
                                            '& .MuiGauge-valueArc': { fill: C.midGreen },
                                        }}
                                    />
                                    <Typography variant="body2" sx={{ color: C.dark, fontWeight: 600 }}>
                                        78% on-time completion
                                    </Typography>
                                </Box>
                            </CardContent>
                        </Card>
                    </Stack>

                    {/* ── Data Table ───────────────────────────────────── */}
                    <Card sx={{ borderRadius: 3, border: `1.5px solid ${C.paleGreen}`, boxShadow: 'none' }}>
                        <CardContent>
                            <Box sx={{ mb: 2 }}>
                                <Typography variant="h6" sx={{ fontWeight: 700, color: C.dark }}>
                                    Report Records
                                </Typography>
                                <Typography variant="body2" color="text.secondary">
                                    Detailed listing of individual report entries with status.
                                </Typography>
                            </Box>
                            <DataGrid
                                rows={rows}
                                columns={columns}
                                initialState={{ pagination: { paginationModel: { pageSize: 5 } } }}
                                pageSizeOptions={[5]}
                                checkboxSelection
                                disableRowSelectionOnClick
                                sx={{
                                    border: 'none',
                                    '& .MuiDataGrid-columnHeader': { backgroundColor: C.paleGreen, color: C.dark, fontWeight: 700 },
                                    '& .MuiDataGrid-row:hover': { backgroundColor: C.lightYellow },
                                    '& .MuiDataGrid-cell, & .MuiDataGrid-columnHeader': { outline: 'none' },
                                    '& .MuiCheckbox-root.Mui-checked': { color: C.midGreen },
                                }}
                            />
                        </CardContent>
                    </Card>
                </Stack>
            </Box>
        </Box>
    );
};

export default ReportsPage;